### ISSUE TITLE
Add support for loading GPT4ALL models

### ISSUE THREAD

**Issue by Priyamakeshwari** [Priyamakeshwari/TeachGPT#10]
Allow users to load GPT4ALL models in load_model function in main.py

**Comment by Rishabh-git10** [comment]
Hey, I am having trouble running the project.
Can you provide me instructions to run it.
I have installed everything where error came, but still it's not running.
It will also be helpful if you provide me requirements.txt

**Comment by Priyamakeshwari** [comment]
Can you share a screen short of what error your getting?

**Comment by Rishabh-git10** [comment]
Ya, I figured it out.
Also, do I replace llama cpp with gpt4all or give it as an alternative ?

**Comment by Priyamakeshwari** [comment]
No, You need to add additionally

**Comment by Rishabh-git10** [comment]
Ok.
Do I write a input line, if someone wants LlamaCpp or GPT4All using input and parse it into model_type or something else.

**Comment by Rishabh-git10** [comment]
Also, do I need to make changes to config.py too as it is routed to LlamaCpp only

**Comment by Priyamakeshwari** [comment]
@Rishabh-git10  yes you have to makes changes in config.py and you need not write any input line , it is not required .

**Comment by Rishabh-git10** [comment]
@Priyamakeshwari hey, are you accepting pull requests or not ?
