### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by Priyamakeshwari** [Priyamakeshwari/TeachGPT#17]
To add documentation for the entire code base for easy understanding and helping future contributors to understand the code easily.
 The documentation should be in the formatted.

Below is the example for documenting a function.

```python

def add(a, b):
    """
    Adds two numbers and returns the result.
    
    Args:
        a (int): The first number.
        b (int): The second number.
    
    Returns:
        int: The sum of `a` and `b`.
    """
    return a + b

```

**Comment by harshita1611** [comment]
Hey, I would like to work on this issue, can you please assign it to me
